# Register user

# Dummy user info
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "name":"SAM",
    "email":"samueloluwasegun999@gmail.com",
    "password":"sagemode2020"
}